import './globals.css'
import {Inter} from 'next/font/google'
import Header from "@/components/Header";
import classNames from "classnames";

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={classNames(inter.className)}>
        <Header/>
        <main>
            {children}
        </main>
        <footer className="footer">
            Created with ❤️<br/>by Kim & Stephan
        </footer>
        </body>
        </html>
    )
}
